extern const GeoLayout wf_area_1_geo[];
extern const GeoLayout wf_area_1[];
extern const Collision wf_area_1_collision[];
extern const MacroObject wf_area_1_macro_objs[];
extern Lights1 wf_dl_Material_001_f3d_lights;
extern Lights1 wf_dl_Material1_f3d_lights;
extern Lights1 wf_dl_Material2_f3d_lights;
extern Lights1 wf_dl_Material3_f3d_lights;
extern u8 wf_dl_Material_ci8[];
extern u8 wf_dl_Material_ci8_pal_rgba16[];
extern u8 wf_dl_Material1_ci8[];
extern u8 wf_dl_Material1_ci8_pal_rgba16[];
extern u8 wf_dl_Material2_ci8[];
extern u8 wf_dl_Material2_ci8_pal_rgba16[];
extern u8 wf_dl_Material3_ci4[];
extern u8 wf_dl_Material3_ci4_pal_rgba16[];
extern Vtx wf_dl_epic_planet_mesh_vtx_0[90];
extern Gfx wf_dl_epic_planet_mesh_tri_0[];
extern Vtx wf_dl_epic_planet_mesh_vtx_1[354];
extern Gfx wf_dl_epic_planet_mesh_tri_1[];
extern Vtx wf_dl_epic_planet_mesh_vtx_2[71];
extern Gfx wf_dl_epic_planet_mesh_tri_2[];
extern Vtx wf_dl_epic_planet_mesh_vtx_3[286];
extern Gfx wf_dl_epic_planet_mesh_tri_3[];
extern Gfx mat_wf_dl_Material_001_f3d[];
extern Gfx mat_revert_wf_dl_Material_001_f3d[];
extern Gfx mat_wf_dl_Material1_f3d[];
extern Gfx mat_revert_wf_dl_Material1_f3d[];
extern Gfx mat_wf_dl_Material2_f3d[];
extern Gfx mat_revert_wf_dl_Material2_f3d[];
extern Gfx mat_wf_dl_Material3_f3d[];
extern Gfx mat_revert_wf_dl_Material3_f3d[];
extern Gfx wf_dl_epic_planet_mesh[];
extern Gfx wf_dl_material_revert_render_settings[];
