#ifndef DIALOG_PROCS_H
#define DIALOG_PROCS_H

enum DialogProcs {
    DIALOG_PROC_PLAY_MUSIC_BBH,
    DIALOG_PROC_PLAY_MUSIC_SLIDE,
    DIALOG_PROC_PLAY_MUSIC_FILE_SELECT,
    DIALOG_PROC_PLAY_MUSIC_DDD,
    DIALOG_PROC_4,
    DIALOG_PROC_5
};

#endif
