#ifndef DIALOG_IDS
#define DIALOG_IDS

enum DialogHeaderColors {
    DIALOG_HEADER_ORANGE,
    DIALOG_HEADER_BLUE,
    DIALOG_HEADER_GREEN
};

// MUST MATCH WITH dialogs.h
enum DialogId {
    DIALOG_TEST,
    DIALOG_HIFUMI_INTRO,
    DIALOG_GAME_START,
    DIALOG_CHANGE_MUSIC,
    DIALOG_CHANGE_MUSIC_BBH,
    DIALOG_CHANGE_MUSIC_KOOPA_FINAL,
    DIALOG_CHANGE_MUSIC_FILE_SELECT,
    DIALOG_CHANGE_MUSIC_DDD,
    DIALOG_COUNT
};

// MUST MATCH WITH sPortraitTable IN ingame_menu.c (except for PORT_NONE)
enum DialogPortraits {
    PORT_NONE,
    PORT_JANAI_NEUTRAL,
    PORT_KYOKO_NEUTRAL
};

#endif
